
import React from 'react';
import Header from '@/components/Header';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { BookOpen, FileText, FileSearch, LayoutDashboard } from 'lucide-react';

const Docs = () => {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Header />
      
      <main className="flex-1 container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">Documentation</h1>
            <p className="text-gray-600">Learn how to use DNS Sentinel effectively</p>
          </div>
          
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
            <Tabs defaultValue="getting-started">
              <div className="border-b px-6">
                <TabsList className="w-full h-14 bg-transparent">
                  <TabsTrigger value="getting-started" className="data-[state=active]:bg-gray-100 rounded-md">
                    <BookOpen className="h-4 w-4 mr-2" />
                    Getting Started
                  </TabsTrigger>
                  <TabsTrigger value="upload-analyze" className="data-[state=active]:bg-gray-100 rounded-md">
                    <FileText className="h-4 w-4 mr-2" />
                    Upload & Analyze
                  </TabsTrigger>
                  <TabsTrigger value="understanding-results" className="data-[state=active]:bg-gray-100 rounded-md">
                    <FileSearch className="h-4 w-4 mr-2" />
                    Understanding Results
                  </TabsTrigger>
                </TabsList>
              </div>
              
              <div className="p-6">
                <TabsContent value="getting-started" className="mt-0 space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold text-gray-900 mb-4">Welcome to DNS Sentinel</h2>
                    <p className="text-gray-700 mb-4">
                      DNS Sentinel is an AI-powered tool designed to detect DNS tunneling and other suspicious DNS activities in your network traffic.
                    </p>
                    <p className="text-gray-700 mb-4">
                      DNS tunneling is a technique that encodes data of other programs or protocols in DNS queries and responses. 
                      Malicious actors can use this technique to bypass firewalls, exfiltrate data, or establish command and control channels.
                    </p>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium text-gray-900 mb-3">Key Features</h3>
                    <ul className="list-disc pl-6 space-y-2 text-gray-700">
                      <li>Upload network capture files (.pcap) or CSV files with DNS query data</li>
                      <li>AI-powered analysis of DNS traffic patterns</li>
                      <li>Detection of suspicious domain names that may indicate tunneling activity</li>
                      <li>Detailed results with confidence scores and entropy metrics</li>
                      <li>Filtering and search capabilities for easy investigation</li>
                    </ul>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium text-gray-900 mb-3">System Requirements</h3>
                    <p className="text-gray-700 mb-2">
                      DNS Sentinel is a web-based application that runs in your browser. For optimal performance, we recommend:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 text-gray-700">
                      <li>Modern web browser (Chrome, Firefox, Safari, Edge)</li>
                      <li>2GB+ of free RAM</li>
                      <li>Stable internet connection</li>
                    </ul>
                  </div>
                </TabsContent>
                
                <TabsContent value="upload-analyze" className="mt-0 space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold text-gray-900 mb-4">Uploading and Analyzing DNS Data</h2>
                    <p className="text-gray-700 mb-4">
                      DNS Sentinel accepts two types of input files for analysis:
                    </p>
                    
                    <div className="bg-gray-50 p-4 rounded-lg mb-6">
                      <h4 className="font-medium text-gray-900 mb-2">PCAP Files</h4>
                      <p className="text-gray-700 mb-2">
                        Network capture files containing raw packet data. Our system will extract DNS queries from these files.
                      </p>
                      <ul className="list-disc pl-6 space-y-1 text-gray-700 text-sm">
                        <li>Generated by tools like Wireshark, tcpdump, etc.</li>
                        <li>Maximum file size: 100MB</li>
                        <li>Supported formats: .pcap, .pcapng</li>
                      </ul>
                    </div>
                    
                    <div className="bg-gray-50 p-4 rounded-lg">
                      <h4 className="font-medium text-gray-900 mb-2">CSV Files</h4>
                      <p className="text-gray-700 mb-2">
                        Spreadsheet files containing DNS query data in a specific format.
                      </p>
                      <ul className="list-disc pl-6 space-y-1 text-gray-700 text-sm">
                        <li>Must include columns: timestamp, domain, query_type, client_ip</li>
                        <li>Maximum file size: 50MB</li>
                        <li>UTF-8 encoding required</li>
                      </ul>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium text-gray-900 mb-3">Uploading Process</h3>
                    <ol className="list-decimal pl-6 space-y-3 text-gray-700">
                      <li>
                        <p className="font-medium">Navigate to the Dashboard</p>
                        <p className="text-sm">Click on the Dashboard link in the top navigation or go to the home page.</p>
                      </li>
                      <li>
                        <p className="font-medium">Drag and drop your file</p>
                        <p className="text-sm">Drag your PCAP or CSV file onto the upload area, or click to browse your files.</p>
                      </li>
                      <li>
                        <p className="font-medium">Verify file selection</p>
                        <p className="text-sm">Ensure the correct file is selected and meets the size limitations.</p>
                      </li>
                      <li>
                        <p className="font-medium">Click "Run AI Analysis"</p>
                        <p className="text-sm">Initiate the analysis process. This may take a few moments depending on file size.</p>
                      </li>
                      <li>
                        <p className="font-medium">Wait for processing</p>
                        <p className="text-sm">The system will show a progress indicator while analyzing your data.</p>
                      </li>
                    </ol>
                  </div>
                  
                  <div className="bg-dns-primary/5 p-4 rounded-lg border border-dns-primary/10">
                    <h4 className="font-medium text-gray-900 mb-2">Tips for Best Results</h4>
                    <ul className="list-disc pl-6 space-y-1 text-gray-700 text-sm">
                      <li>Ensure your capture files contain complete DNS transactions</li>
                      <li>For large networks, split data into multiple files under 100MB</li>
                      <li>Include a representative sample period (at least 1 hour of traffic)</li>
                      <li>Clean your data to remove incomplete entries if using CSV format</li>
                    </ul>
                  </div>
                </TabsContent>
                
                <TabsContent value="understanding-results" className="mt-0 space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold text-gray-900 mb-4">Understanding Your Analysis Results</h2>
                    <p className="text-gray-700 mb-4">
                      After analysis, DNS Sentinel provides comprehensive results that help you identify potential DNS tunneling activities. Here's how to interpret the data:
                    </p>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium text-gray-900 mb-3">Summary Metrics</h3>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                      <div className="bg-gray-50 p-4 rounded-lg">
                        <h4 className="font-medium text-gray-900 mb-2">Total Queries</h4>
                        <p className="text-sm text-gray-600">
                          The total number of DNS queries analyzed from your uploaded file.
                        </p>
                      </div>
                      
                      <div className="bg-gray-50 p-4 rounded-lg">
                        <h4 className="font-medium text-gray-900 mb-2">Suspicious Queries</h4>
                        <p className="text-sm text-gray-600">
                          Number of queries flagged as potentially malicious by our AI model.
                        </p>
                      </div>
                      
                      <div className="bg-gray-50 p-4 rounded-lg">
                        <h4 className="font-medium text-gray-900 mb-2">Benign Queries</h4>
                        <p className="text-sm text-gray-600">
                          Number of queries classified as normal, legitimate DNS traffic.
                        </p>
                      </div>
                      
                      <div className="bg-gray-50 p-4 rounded-lg">
                        <h4 className="font-medium text-gray-900 mb-2">Suspicious Rate</h4>
                        <p className="text-sm text-gray-600">
                          Percentage of total queries classified as suspicious. Rates above 5% may indicate tunneling activity.
                        </p>
                      </div>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium text-gray-900 mb-3">Detailed Results Table</h3>
                    <p className="text-gray-700 mb-3">
                      The detailed table shows individual DNS queries with the following information:
                    </p>
                    
                    <div className="space-y-4">
                      <div className="bg-gray-50 rounded-lg overflow-hidden">
                        <div className="bg-gray-100 p-2">
                          <h4 className="font-medium text-gray-900">Domain Name</h4>
                        </div>
                        <div className="p-4">
                          <p className="text-sm text-gray-600">
                            The domain name queried. Unusually long or complex domain names may indicate tunneling.
                          </p>
                        </div>
                      </div>
                      
                      <div className="bg-gray-50 rounded-lg overflow-hidden">
                        <div className="bg-gray-100 p-2">
                          <h4 className="font-medium text-gray-900">Query Type</h4>
                        </div>
                        <div className="p-4">
                          <p className="text-sm text-gray-600">
                            The type of DNS record requested (A, AAAA, TXT, etc). Tunneling often uses TXT, CNAME, or MX records.
                          </p>
                        </div>
                      </div>
                      
                      <div className="bg-gray-50 rounded-lg overflow-hidden">
                        <div className="bg-gray-100 p-2">
                          <h4 className="font-medium text-gray-900">Length</h4>
                        </div>
                        <div className="p-4">
                          <p className="text-sm text-gray-600">
                            The length of the domain name in characters. Unusually long domains may indicate encoded data.
                          </p>
                        </div>
                      </div>
                      
                      <div className="bg-gray-50 rounded-lg overflow-hidden">
                        <div className="bg-gray-100 p-2">
                          <h4 className="font-medium text-gray-900">Entropy</h4>
                        </div>
                        <div className="p-4">
                          <p className="text-sm text-gray-600">
                            Measure of randomness in the domain name. Higher values (&gt;3.5) may indicate encoded data being tunneled.
                          </p>
                        </div>
                      </div>
                      
                      <div className="bg-gray-50 rounded-lg overflow-hidden">
                        <div className="bg-gray-100 p-2">
                          <h4 className="font-medium text-gray-900">Classification</h4>
                        </div>
                        <div className="p-4">
                          <p className="text-sm text-gray-600">
                            The AI model's assessment: Benign (normal) or Suspicious (potential tunneling activity).
                          </p>
                        </div>
                      </div>
                      
                      <div className="bg-gray-50 rounded-lg overflow-hidden">
                        <div className="bg-gray-100 p-2">
                          <h4 className="font-medium text-gray-900">Confidence</h4>
                        </div>
                        <div className="p-4">
                          <p className="text-sm text-gray-600">
                            The AI model's confidence level in its classification decision.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-medium text-gray-900 mb-3">Filtering and Searching</h3>
                    <p className="text-gray-700 mb-3">
                      Use the search box to find specific domains or the filter buttons to focus on suspicious or benign queries. The table allows pagination to navigate through large result sets.
                    </p>
                  </div>
                  
                  <div className="bg-dns-primary/5 p-4 rounded-lg border border-dns-primary/10">
                    <h4 className="font-medium text-gray-900 mb-2">Interpreting Suspicious Results</h4>
                    <p className="text-sm text-gray-700 mb-3">
                      When reviewing suspicious queries, consider these factors:
                    </p>
                    <ul className="list-disc pl-6 space-y-1 text-gray-700 text-sm">
                      <li>Higher confidence percentage indicates stronger evidence of tunneling</li>
                      <li>Groups of suspicious queries from the same subdomain pattern may indicate systematic abuse</li>
                      <li>Investigate domains with unusual entropy values or excessive length first</li>
                      <li>Some legitimate services may trigger false positives (content delivery networks, etc.)</li>
                    </ul>
                  </div>
                </TabsContent>
              </div>
            </Tabs>
          </div>
        </div>
      </main>
      
      <footer className="bg-white border-t border-gray-200 mt-auto">
        <div className="container mx-auto px-4 py-6">
          <div className="text-center text-sm text-gray-500">
            <p>© 2025 DNS Sentinel. AI-powered DNS security monitoring.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Docs;
